apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
    spec:
      containers:
        - name: market-data
          image: cryptoflow:latest
          imagePullPolicy: IfNotPresent
          args: ["market_data"]
          envFrom:
            - configMapRef:
                name: cryptoflow-config
            - secretRef:
                name: cryptoflow-secrets
          ports:
            - containerPort: 50051 # gRPC port
